export const experience = [
  {
    role: "Senior Operational Manager",
    organization: "Technical Team, SIES GST",
    dates: "August 2026 — Present",
    category: "Leadership / Operations",
    description: "Senior operational role with the Technical Team at SIES GST.",
    tags: ["Operations", "Technical team", "Leadership"],
  },
  {
    role: "Design Coordinator",
    organization: "TEDxSIESGST",
    dates: "September 2026 — October 2026",
    category: "Design / Events",
    description: "Contributed to the TEDxSIESGST design team, working on merchandise and banner designs for the event.",
    tags: ["Merchandise design", "Banner design", "Teamwork"],
  },
  {
    role: "Junior Operations Manager",
    organization: "Technical Team, SIES GST",
    dates: "August 2025 — July 2026",
    category: "Leadership / Operations",
    description: "Junior Operations Manager with the Technical Team at SIES GST.",
    tags: ["Operations", "Technical team"],
  },
  {
    role: "Co-Founder",
    organization: "Srishti Green Decor",
    dates: "June 2019 — Present",
    category: "Business / Digital product",
    description: "Co-founded a handcrafted, eco-friendly home décor business. Built its website and contributed to social media, newsletters, and its presence on e-commerce platforms.",
    tags: ["Entrepreneurship", "Web development", "E-commerce"],
    href: "https://srishtigreendecor.com",
  },
  {
    role: "Event Head — Lakshya 2025",
    organization: "SIES GST Students’ Council",
    dates: "December 2024 — February 2025",
    category: "Event leadership",
    description: "Served as the event head for Turf Football at Lakshya 2025, SIES GST’s annual sports event.",
    tags: ["Event planning", "Football", "Coordination"],
  },
  {
    role: "Volunteer",
    organization: "Dream Sports Foundation",
    dates: "June 2024",
    category: "Volunteering / Communication",
    description: "Acted as a liaison between match commissioners, referees, and players during an under-18 football championship, helping communication run smoothly.",
    tags: ["Communication", "Teamwork", "Sport"],
  },
];
